# Onehalf Colorscheme for Kitty
# Based on https://github.com/sonph/onehalf
# By https://github.com/dbinary

font_family Fira Code Retina Nerd Font Complete Mono
# font_family BlexMono Nerd Font Mono
# font_family mononoki nerd font mono
font_size 12


# special
foreground       #9ea3c0
cursor           #9ea3c0
background       #222433

# black
color0   #000000
color8   #5d6872

# red
color1   #ff6e67
color9   #d5635e

# green
color2   #7cbe8c
color10  #6ca97a

# yellow
color3   #f4f99d
color11  #b3c580

# blue
color4   #929be5
color12  #838cd6

# magenta
color5   #ff92d0
color13  #ff92d0

# cyan
color6   #2aacbd
color14  #2aacbd

# white
color7   #c7c7c7
color15  #ffffff
vim:ft=kitty

## name: Tokyo Night
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty_tokyonight_night.conf


#background #1a1b26
#foreground #c0caf5
#selection_background #33467C
#selection_foreground #c0caf5
#url_color #73daca
#cursor #c0caf5

## Tabs
#active_tab_background #7aa2f7
#active_tab_foreground #1f2335
#inactive_tab_background #292e42
#inactive_tab_foreground #545c7e
##tab_bar_background #15161E

## normal
#color0 #15161E
#color1 #f7768e
#color2 #9ece6a
#color3 #e0af68
#color4 #7aa2f7
#color5 #bb9af7
#color6 #7dcfff
#color7 #a9b1d6

## bright
#color8 #414868
#color9 #f7768e
#color10 #9ece6a
#color11 #e0af68
#color12 #7aa2f7
#color13 #bb9af7
#color14 #7dcfff
#color15 #c0caf5

## extended colors
#color16 #ff9e64
#color17 #db4b4b
